POST http://localhost:8080/books/add
Accept: application/json
Content-Type: application/json

{
  "title": "first",
  "publicationDate": "2023-03-04"
}

####
GET http://localhost:8080/books/all
Accept: application/json

####

