POST http://localhost:8080/books/add
Accept: application/json
Content-Type: application/json

{
  "title": "second",
  "publicationDate": "2022-03-04"
}

####
GET http://localhost:8080/books/all
Accept: application/json

####
GET http://localhost:8080/books/all?title=first
Accept: application/json

####
GET http://localhost:8080/books/find?date=2023-03-04
Accept: application/json